### PR TITLE
Add saved messages feature

### PR DESCRIPTION
**Pull request by Skrilltrax**
This is a rough draft atm and does not include the ability to remove saved messages.

### CODE REVIEW

**Comment by msfjarvis** [comment]
The liked flag is still not unset in the main list until we reload posts. I know why this happens but do not have any good ideas to resolve it right now.

**Comment by Skrilltrax** [comment]
I don't think it's worth changing the liked flag until the list reloads because we will have to do a list refresh and since we are removing it from savedPostsDB anyway it should not cause any issues.

**Comment by Skrilltrax** [comment]
BTW, I think we should also do this in case of a removed post.
```      val tempList = _posts.value
_posts.value = tempList.map {
	if (it.shortId == post.shortId) it.isLiked = false
    it
}
```

**Comment by msfjarvis** [comment]
> BTW, I think we should also do this in case of a removed post.
> 
> ```
> _posts.value = tempList.map {
> 	if (it.shortId == post.shortId) it.isLiked = false
>     it
> }
> ```

Yeah that'll probably fix the last bug.

**Review by msfjarvis — APPROVED** [review]

**Pull request merged**
