### PR TITLE
Run screenshot tests in CI

### PR DESCRIPTION
**Pull request by msfjarvis**
`connectedCheck` seemingly does not include Shot tests so we need to explicitly run them. This also updates the screenshots to be from an emulator that exactly matches the one in CI.

bors r+

### CODE REVIEW

**Comment by msfjarvis** [comment]
bors retry

**Comment by Skrilltrax** [comment]
bors retry

**Comment by Skrilltrax** [comment]
bors retry

**Comment by msfjarvis** [comment]
The 4a is not part of the default set, we'll need to hack some things up. I'm working on it.

**Comment by msfjarvis** [comment]
Fuck it

**Comment by msfjarvis** [comment]
bors retry

**Comment by msfjarvis** [comment]
I created separate Pixel XL emulators from the CLI and the AVD Manager UI, both generated the same screenshots so I'm 100% lost on what is wrong with this one.

**Comment by msfjarvis** [comment]
bors try

**Comment by msfjarvis** [comment]
bors r+ p=1000

Better fucking work

**Comment by msfjarvis** [comment]
Right, Actions doesn't have networking right now for some reason. I'm going to close this tab before I start throwing things.

**Comment by msfjarvis** [comment]
bors retry

**Pull request closed without merging**
