### PR TITLE
Fix cache issues

### PR DESCRIPTION
**Pull request by Skrilltrax**

### CODE REVIEW

**Review by msfjarvis — APPROVED** [review]
Seems reasonable. Maybe at some point we can eliminate the cache entirely to avoid having to keep two sources of truth (cache and db) in sync.

bors r+

**Comment by msfjarvis** [comment]
bors r-

Missed that it's a draft

**Comment by Skrilltrax** [comment]
Yeah, I mean we can avoid cache entirely right now but it'll slow down the app considerably (since we check if the post is available in the DB). Can you test it and check if it is working fine for you? The viewmodel's observer is not being called for me.

**Comment by msfjarvis** [comment]
> Yeah, I mean we can avoid cache entirely right now but it'll slow down the app considerably (since we check if the post is available in the DB). Can you test it and check if it is working fine for you? The viewmodel's observer is not being called for me.

It's still broken for me. I'm fine with saving being slower if it improves reliability.

**Comment by Skrilltrax** [comment]
Hey, I Have an exam on 4th, will fix this after that.

**Comment by msfjarvis** [comment]
> Hey, I Have an exam on 4th, will fix this after that.

Yeah no worries. Best of luck with the exam!

**Comment by Skrilltrax** [comment]
@msfjarvis can you test it on your device. This seems to fix the issue for me.

**Review by msfjarvis — APPROVED** [review]
bors r+

**Pull request merged**
