### PR TITLE
Move paging to common module

### PR DESCRIPTION
**Pull request by Skrilltrax**

### CODE REVIEW

**Comment by Skrilltrax** [comment]
@msfjarvis can you review the code (needs some cleanup like removing the reload method and spotless)

**Comment by msfjarvis** [comment]
Did some initial work on this https://github.com/msfjarvis/multiplatform-paging/tree/hs/invalidate-support

**Comment by msfjarvis** [comment]
Rebased

**Comment by msfjarvis** [comment]
Pursuing #313 instead

**Pull request closed without merging**
